### ISSUE TITLE
Not starting stream

### ISSUE THREAD

**Issue by Strit** [xbmc-danish-addons/plugin.video.dr.dk.live#3]
When clicking the menu items, it gives a very short blink and stays on the menu.
I've tested with most of DR's channels.

Anyone else have this issue?

**Comment by donkeylobster** [comment]
Yes, i see the same. 

I will suggest you to use the plugin "DR TV" for live streams from DR.

**Comment by Strit** [comment]
Didn't know DR TV included the live streams. We have only use dit for watching the archives.
Will give that a try.
